# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(466, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(466, 700))
        MainWindow.setMaximumSize(QtCore.QSize(466, 700))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 489, 710))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gr_input = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gr_input.sizePolicy().hasHeightForWidth())
        self.gr_input.setSizePolicy(sizePolicy)
        self.gr_input.setMinimumSize(QtCore.QSize(430, 0))
        self.gr_input.setMaximumSize(QtCore.QSize(430, 16777215))
        self.gr_input.setObjectName(_fromUtf8("gr_input"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.gr_input)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lb_run = QtGui.QLabel(self.gr_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_run.sizePolicy().hasHeightForWidth())
        self.lb_run.setSizePolicy(sizePolicy)
        self.lb_run.setMinimumSize(QtCore.QSize(40, 0))
        self.lb_run.setMaximumSize(QtCore.QSize(40, 24))
        self.lb_run.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_run.setObjectName(_fromUtf8("lb_run"))
        self.horizontalLayout_4.addWidget(self.lb_run)
        self.le_run = QtGui.QLineEdit(self.gr_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_run.sizePolicy().hasHeightForWidth())
        self.le_run.setSizePolicy(sizePolicy)
        self.le_run.setMinimumSize(QtCore.QSize(280, 0))
        self.le_run.setMaximumSize(QtCore.QSize(16777215, 24))
        self.le_run.setObjectName(_fromUtf8("le_run"))
        self.horizontalLayout_4.addWidget(self.le_run)
        self.pb_run = QtGui.QPushButton(self.gr_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_run.sizePolicy().hasHeightForWidth())
        self.pb_run.setSizePolicy(sizePolicy)
        self.pb_run.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pb_run.setObjectName(_fromUtf8("pb_run"))
        self.horizontalLayout_4.addWidget(self.pb_run)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lb_map = QtGui.QLabel(self.gr_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_map.sizePolicy().hasHeightForWidth())
        self.lb_map.setSizePolicy(sizePolicy)
        self.lb_map.setMinimumSize(QtCore.QSize(40, 0))
        self.lb_map.setMaximumSize(QtCore.QSize(40, 24))
        self.lb_map.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_map.setObjectName(_fromUtf8("lb_map"))
        self.horizontalLayout_2.addWidget(self.lb_map)
        self.le_map = QtGui.QLineEdit(self.gr_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_map.sizePolicy().hasHeightForWidth())
        self.le_map.setSizePolicy(sizePolicy)
        self.le_map.setMinimumSize(QtCore.QSize(280, 0))
        self.le_map.setMaximumSize(QtCore.QSize(16777215, 24))
        self.le_map.setObjectName(_fromUtf8("le_map"))
        self.horizontalLayout_2.addWidget(self.le_map)
        self.pb_map = QtGui.QPushButton(self.gr_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_map.sizePolicy().hasHeightForWidth())
        self.pb_map.setSizePolicy(sizePolicy)
        self.pb_map.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pb_map.setObjectName(_fromUtf8("pb_map"))
        self.horizontalLayout_2.addWidget(self.pb_map)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.gr_input)
        self.gr_stage = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gr_stage.sizePolicy().hasHeightForWidth())
        self.gr_stage.setSizePolicy(sizePolicy)
        self.gr_stage.setMinimumSize(QtCore.QSize(440, 0))
        self.gr_stage.setMaximumSize(QtCore.QSize(440, 16777215))
        self.gr_stage.setObjectName(_fromUtf8("gr_stage"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.gr_stage)
        self.horizontalLayout_16.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.tb_align = QtGui.QTabWidget(self.gr_stage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_align.sizePolicy().hasHeightForWidth())
        self.tb_align.setSizePolicy(sizePolicy)
        self.tb_align.setMinimumSize(QtCore.QSize(220, 190))
        self.tb_align.setMaximumSize(QtCore.QSize(220, 190))
        self.tb_align.setBaseSize(QtCore.QSize(0, 0))
        self.tb_align.setTabPosition(QtGui.QTabWidget.West)
        self.tb_align.setObjectName(_fromUtf8("tb_align"))
        self.tab_print = QtGui.QWidget()
        self.tab_print.setObjectName(_fromUtf8("tab_print"))
        self.lb_printpix = QtGui.QLabel(self.tab_print)
        self.lb_printpix.setGeometry(QtCore.QRect(0, 0, 191, 181))
        self.lb_printpix.setText(_fromUtf8(""))
        self.lb_printpix.setPixmap(QtGui.QPixmap(_fromUtf8(":/alignment/alignprint.png")))
        self.lb_printpix.setScaledContents(False)
        self.lb_printpix.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_printpix.setObjectName(_fromUtf8("lb_printpix"))
        self.tb_align.addTab(self.tab_print, _fromUtf8(""))
        self.tab_wafer = QtGui.QWidget()
        self.tab_wafer.setObjectName(_fromUtf8("tab_wafer"))
        self.lb_waferpix = QtGui.QLabel(self.tab_wafer)
        self.lb_waferpix.setGeometry(QtCore.QRect(0, 0, 191, 181))
        self.lb_waferpix.setText(_fromUtf8(""))
        self.lb_waferpix.setPixmap(QtGui.QPixmap(_fromUtf8(":/alignment/alignwafer.png")))
        self.lb_waferpix.setScaledContents(False)
        self.lb_waferpix.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_waferpix.setObjectName(_fromUtf8("lb_waferpix"))
        self.tb_align.addTab(self.tab_wafer, _fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.tb_align)
        spacerItem = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lb_stagcoord = QtGui.QLabel(self.gr_stage)
        self.lb_stagcoord.setObjectName(_fromUtf8("lb_stagcoord"))
        self.verticalLayout_8.addWidget(self.lb_stagcoord)
        spacerItem1 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem1)
        self.tw_stage = QtGui.QTableWidget(self.gr_stage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_stage.sizePolicy().hasHeightForWidth())
        self.tw_stage.setSizePolicy(sizePolicy)
        self.tw_stage.setMaximumSize(QtCore.QSize(180, 97))
        self.tw_stage.setObjectName(_fromUtf8("tw_stage"))
        self.tw_stage.setColumnCount(3)
        self.tw_stage.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tw_stage.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tw_stage.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tw_stage.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tw_stage.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tw_stage.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tw_stage.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tw_stage.setItem(0, 0, item)
        self.tw_stage.horizontalHeader().setDefaultSectionSize(54)
        self.tw_stage.horizontalHeader().setMinimumSectionSize(54)
        self.tw_stage.verticalHeader().setVisible(True)
        self.tw_stage.verticalHeader().setDefaultSectionSize(24)
        self.tw_stage.verticalHeader().setMinimumSectionSize(24)
        self.verticalLayout_8.addWidget(self.tw_stage)
        spacerItem2 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.lb_stagz = QtGui.QLabel(self.gr_stage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_stagz.sizePolicy().hasHeightForWidth())
        self.lb_stagz.setSizePolicy(sizePolicy)
        self.lb_stagz.setMinimumSize(QtCore.QSize(32, 0))
        self.lb_stagz.setMaximumSize(QtCore.QSize(32, 24))
        self.lb_stagz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_stagz.setObjectName(_fromUtf8("lb_stagz"))
        self.horizontalLayout_15.addWidget(self.lb_stagz)
        self.le_stagz = QtGui.QLineEdit(self.gr_stage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_stagz.sizePolicy().hasHeightForWidth())
        self.le_stagz.setSizePolicy(sizePolicy)
        self.le_stagz.setMinimumSize(QtCore.QSize(54, 24))
        self.le_stagz.setMaximumSize(QtCore.QSize(54, 24))
        self.le_stagz.setObjectName(_fromUtf8("le_stagz"))
        self.horizontalLayout_15.addWidget(self.le_stagz)
        spacerItem3 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.cb_rotonly = QtGui.QCheckBox(self.gr_stage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_rotonly.sizePolicy().hasHeightForWidth())
        self.cb_rotonly.setSizePolicy(sizePolicy)
        self.cb_rotonly.setMinimumSize(QtCore.QSize(78, 0))
        self.cb_rotonly.setMaximumSize(QtCore.QSize(78, 16777215))
        self.cb_rotonly.setObjectName(_fromUtf8("cb_rotonly"))
        self.horizontalLayout_15.addWidget(self.cb_rotonly)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        spacerItem4 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem4)
        self.le_waferignore = QtGui.QLabel(self.gr_stage)
        self.le_waferignore.setTextFormat(QtCore.Qt.RichText)
        self.le_waferignore.setObjectName(_fromUtf8("le_waferignore"))
        self.verticalLayout_8.addWidget(self.le_waferignore)
        self.lb_rotonly = QtGui.QLabel(self.gr_stage)
        self.lb_rotonly.setTextFormat(QtCore.Qt.RichText)
        self.lb_rotonly.setObjectName(_fromUtf8("lb_rotonly"))
        self.verticalLayout_8.addWidget(self.lb_rotonly)
        self.horizontalLayout_16.addLayout(self.verticalLayout_8)
        self.verticalLayout.addWidget(self.gr_stage)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gr_filter = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gr_filter.sizePolicy().hasHeightForWidth())
        self.gr_filter.setSizePolicy(sizePolicy)
        self.gr_filter.setMinimumSize(QtCore.QSize(220, 90))
        self.gr_filter.setMaximumSize(QtCore.QSize(220, 90))
        self.gr_filter.setObjectName(_fromUtf8("gr_filter"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gr_filter)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lb_keepcode = QtGui.QLabel(self.gr_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_keepcode.sizePolicy().hasHeightForWidth())
        self.lb_keepcode.setSizePolicy(sizePolicy)
        self.lb_keepcode.setMinimumSize(QtCore.QSize(60, 0))
        self.lb_keepcode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_keepcode.setObjectName(_fromUtf8("lb_keepcode"))
        self.horizontalLayout_5.addWidget(self.lb_keepcode)
        self.le_keepcode = QtGui.QLineEdit(self.gr_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_keepcode.sizePolicy().hasHeightForWidth())
        self.le_keepcode.setSizePolicy(sizePolicy)
        self.le_keepcode.setMinimumSize(QtCore.QSize(103, 24))
        self.le_keepcode.setMaximumSize(QtCore.QSize(130, 24))
        self.le_keepcode.setObjectName(_fromUtf8("le_keepcode"))
        self.horizontalLayout_5.addWidget(self.le_keepcode)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lb_omitch = QtGui.QLabel(self.gr_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_omitch.sizePolicy().hasHeightForWidth())
        self.lb_omitch.setSizePolicy(sizePolicy)
        self.lb_omitch.setMinimumSize(QtCore.QSize(60, 0))
        self.lb_omitch.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lb_omitch.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_omitch.setObjectName(_fromUtf8("lb_omitch"))
        self.horizontalLayout_7.addWidget(self.lb_omitch)
        self.le_omitch = QtGui.QLineEdit(self.gr_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_omitch.sizePolicy().hasHeightForWidth())
        self.le_omitch.setSizePolicy(sizePolicy)
        self.le_omitch.setMinimumSize(QtCore.QSize(130, 24))
        self.le_omitch.setMaximumSize(QtCore.QSize(130, 24))
        self.le_omitch.setObjectName(_fromUtf8("le_omitch"))
        self.horizontalLayout_7.addWidget(self.le_omitch)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addWidget(self.gr_filter)
        self.gr_platecoord = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gr_platecoord.sizePolicy().hasHeightForWidth())
        self.gr_platecoord.setSizePolicy(sizePolicy)
        self.gr_platecoord.setMinimumSize(QtCore.QSize(220, 90))
        self.gr_platecoord.setMaximumSize(QtCore.QSize(220, 90))
        self.gr_platecoord.setObjectName(_fromUtf8("gr_platecoord"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gr_platecoord)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lb_xmin = QtGui.QLabel(self.gr_platecoord)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_xmin.sizePolicy().hasHeightForWidth())
        self.lb_xmin.setSizePolicy(sizePolicy)
        self.lb_xmin.setMinimumSize(QtCore.QSize(42, 0))
        self.lb_xmin.setMaximumSize(QtCore.QSize(42, 16777215))
        self.lb_xmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_xmin.setObjectName(_fromUtf8("lb_xmin"))
        self.horizontalLayout_11.addWidget(self.lb_xmin)
        self.le_xmin = QtGui.QLineEdit(self.gr_platecoord)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_xmin.sizePolicy().hasHeightForWidth())
        self.le_xmin.setSizePolicy(sizePolicy)
        self.le_xmin.setMinimumSize(QtCore.QSize(58, 24))
        self.le_xmin.setMaximumSize(QtCore.QSize(58, 24))
        self.le_xmin.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.le_xmin.setObjectName(_fromUtf8("le_xmin"))
        self.horizontalLayout_11.addWidget(self.le_xmin)
        self.lb_xmax = QtGui.QLabel(self.gr_platecoord)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_xmax.sizePolicy().hasHeightForWidth())
        self.lb_xmax.setSizePolicy(sizePolicy)
        self.lb_xmax.setMinimumSize(QtCore.QSize(42, 0))
        self.lb_xmax.setMaximumSize(QtCore.QSize(42, 16777215))
        self.lb_xmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_xmax.setObjectName(_fromUtf8("lb_xmax"))
        self.horizontalLayout_11.addWidget(self.lb_xmax)
        self.le_xmax = QtGui.QLineEdit(self.gr_platecoord)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_xmax.sizePolicy().hasHeightForWidth())
        self.le_xmax.setSizePolicy(sizePolicy)
        self.le_xmax.setMinimumSize(QtCore.QSize(58, 24))
        self.le_xmax.setMaximumSize(QtCore.QSize(58, 24))
        self.le_xmax.setObjectName(_fromUtf8("le_xmax"))
        self.horizontalLayout_11.addWidget(self.le_xmax)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lb_ymin = QtGui.QLabel(self.gr_platecoord)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_ymin.sizePolicy().hasHeightForWidth())
        self.lb_ymin.setSizePolicy(sizePolicy)
        self.lb_ymin.setMinimumSize(QtCore.QSize(42, 0))
        self.lb_ymin.setMaximumSize(QtCore.QSize(42, 16777215))
        self.lb_ymin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_ymin.setObjectName(_fromUtf8("lb_ymin"))
        self.horizontalLayout_6.addWidget(self.lb_ymin)
        self.le_ymin = QtGui.QLineEdit(self.gr_platecoord)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ymin.sizePolicy().hasHeightForWidth())
        self.le_ymin.setSizePolicy(sizePolicy)
        self.le_ymin.setMinimumSize(QtCore.QSize(58, 24))
        self.le_ymin.setMaximumSize(QtCore.QSize(58, 24))
        self.le_ymin.setObjectName(_fromUtf8("le_ymin"))
        self.horizontalLayout_6.addWidget(self.le_ymin)
        self.lb_ymax = QtGui.QLabel(self.gr_platecoord)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_ymax.sizePolicy().hasHeightForWidth())
        self.lb_ymax.setSizePolicy(sizePolicy)
        self.lb_ymax.setMinimumSize(QtCore.QSize(42, 0))
        self.lb_ymax.setMaximumSize(QtCore.QSize(42, 16777215))
        self.lb_ymax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_ymax.setObjectName(_fromUtf8("lb_ymax"))
        self.horizontalLayout_6.addWidget(self.lb_ymax)
        self.le_ymax = QtGui.QLineEdit(self.gr_platecoord)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ymax.sizePolicy().hasHeightForWidth())
        self.le_ymax.setSizePolicy(sizePolicy)
        self.le_ymax.setMinimumSize(QtCore.QSize(58, 24))
        self.le_ymax.setMaximumSize(QtCore.QSize(58, 24))
        self.le_ymax.setObjectName(_fromUtf8("le_ymax"))
        self.horizontalLayout_6.addWidget(self.le_ymax)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addWidget(self.gr_platecoord)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.gr_skip = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gr_skip.sizePolicy().hasHeightForWidth())
        self.gr_skip.setSizePolicy(sizePolicy)
        self.gr_skip.setMinimumSize(QtCore.QSize(200, 150))
        self.gr_skip.setMaximumSize(QtCore.QSize(200, 150))
        self.gr_skip.setObjectName(_fromUtf8("gr_skip"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gr_skip)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.le_sampleskip = QtGui.QLineEdit(self.gr_skip)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_sampleskip.sizePolicy().hasHeightForWidth())
        self.le_sampleskip.setSizePolicy(sizePolicy)
        self.le_sampleskip.setMinimumSize(QtCore.QSize(60, 24))
        self.le_sampleskip.setMaximumSize(QtCore.QSize(60, 24))
        self.le_sampleskip.setObjectName(_fromUtf8("le_sampleskip"))
        self.horizontalLayout_9.addWidget(self.le_sampleskip)
        self.lb_sampleskip = QtGui.QLabel(self.gr_skip)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_sampleskip.sizePolicy().hasHeightForWidth())
        self.lb_sampleskip.setSizePolicy(sizePolicy)
        self.lb_sampleskip.setMinimumSize(QtCore.QSize(50, 0))
        self.lb_sampleskip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_sampleskip.setObjectName(_fromUtf8("lb_sampleskip"))
        self.horizontalLayout_9.addWidget(self.lb_sampleskip)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.le_colskip = QtGui.QLineEdit(self.gr_skip)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_colskip.sizePolicy().hasHeightForWidth())
        self.le_colskip.setSizePolicy(sizePolicy)
        self.le_colskip.setMinimumSize(QtCore.QSize(60, 24))
        self.le_colskip.setMaximumSize(QtCore.QSize(60, 24))
        self.le_colskip.setObjectName(_fromUtf8("le_colskip"))
        self.horizontalLayout_8.addWidget(self.le_colskip)
        self.lb_colskip = QtGui.QLabel(self.gr_skip)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_colskip.sizePolicy().hasHeightForWidth())
        self.lb_colskip.setSizePolicy(sizePolicy)
        self.lb_colskip.setMinimumSize(QtCore.QSize(50, 0))
        self.lb_colskip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_colskip.setObjectName(_fromUtf8("lb_colskip"))
        self.horizontalLayout_8.addWidget(self.lb_colskip)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.le_rowskip = QtGui.QLineEdit(self.gr_skip)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_rowskip.sizePolicy().hasHeightForWidth())
        self.le_rowskip.setSizePolicy(sizePolicy)
        self.le_rowskip.setMinimumSize(QtCore.QSize(60, 24))
        self.le_rowskip.setMaximumSize(QtCore.QSize(60, 24))
        self.le_rowskip.setObjectName(_fromUtf8("le_rowskip"))
        self.horizontalLayout_14.addWidget(self.le_rowskip)
        self.lb_rowskip = QtGui.QLabel(self.gr_skip)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_rowskip.sizePolicy().hasHeightForWidth())
        self.lb_rowskip.setSizePolicy(sizePolicy)
        self.lb_rowskip.setMinimumSize(QtCore.QSize(50, 0))
        self.lb_rowskip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_rowskip.setObjectName(_fromUtf8("lb_rowskip"))
        self.horizontalLayout_14.addWidget(self.lb_rowskip)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.le_atskip = QtGui.QLineEdit(self.gr_skip)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_atskip.sizePolicy().hasHeightForWidth())
        self.le_atskip.setSizePolicy(sizePolicy)
        self.le_atskip.setMinimumSize(QtCore.QSize(60, 24))
        self.le_atskip.setMaximumSize(QtCore.QSize(60, 24))
        self.le_atskip.setObjectName(_fromUtf8("le_atskip"))
        self.horizontalLayout_10.addWidget(self.le_atskip)
        self.lb_atskip = QtGui.QLabel(self.gr_skip)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_atskip.sizePolicy().hasHeightForWidth())
        self.lb_atskip.setSizePolicy(sizePolicy)
        self.lb_atskip.setMinimumSize(QtCore.QSize(50, 0))
        self.lb_atskip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_atskip.setObjectName(_fromUtf8("lb_atskip"))
        self.horizontalLayout_10.addWidget(self.lb_atskip)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12.addWidget(self.gr_skip)
        self.gr_sample = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gr_sample.sizePolicy().hasHeightForWidth())
        self.gr_sample.setSizePolicy(sizePolicy)
        self.gr_sample.setMinimumSize(QtCore.QSize(285, 136))
        self.gr_sample.setMaximumSize(QtCore.QSize(285, 136))
        self.gr_sample.setObjectName(_fromUtf8("gr_sample"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gr_sample)
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.te_samplelist = QtGui.QTextEdit(self.gr_sample)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_samplelist.sizePolicy().hasHeightForWidth())
        self.te_samplelist.setSizePolicy(sizePolicy)
        self.te_samplelist.setMinimumSize(QtCore.QSize(280, 68))
        self.te_samplelist.setMaximumSize(QtCore.QSize(280, 68))
        self.te_samplelist.setObjectName(_fromUtf8("te_samplelist"))
        self.verticalLayout_3.addWidget(self.te_samplelist)
        spacerItem5 = QtGui.QSpacerItem(20, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.lb_samplemin = QtGui.QLabel(self.gr_sample)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_samplemin.sizePolicy().hasHeightForWidth())
        self.lb_samplemin.setSizePolicy(sizePolicy)
        self.lb_samplemin.setMinimumSize(QtCore.QSize(80, 0))
        self.lb_samplemin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lb_samplemin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_samplemin.setObjectName(_fromUtf8("lb_samplemin"))
        self.horizontalLayout_13.addWidget(self.lb_samplemin)
        self.le_samplemin = QtGui.QLineEdit(self.gr_sample)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_samplemin.sizePolicy().hasHeightForWidth())
        self.le_samplemin.setSizePolicy(sizePolicy)
        self.le_samplemin.setMinimumSize(QtCore.QSize(60, 24))
        self.le_samplemin.setMaximumSize(QtCore.QSize(60, 24))
        self.le_samplemin.setObjectName(_fromUtf8("le_samplemin"))
        self.horizontalLayout_13.addWidget(self.le_samplemin)
        self.lb_samplemax = QtGui.QLabel(self.gr_sample)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_samplemax.sizePolicy().hasHeightForWidth())
        self.lb_samplemax.setSizePolicy(sizePolicy)
        self.lb_samplemax.setMinimumSize(QtCore.QSize(80, 0))
        self.lb_samplemax.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lb_samplemax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_samplemax.setObjectName(_fromUtf8("lb_samplemax"))
        self.horizontalLayout_13.addWidget(self.lb_samplemax)
        self.le_samplemax = QtGui.QLineEdit(self.gr_sample)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_samplemax.sizePolicy().hasHeightForWidth())
        self.le_samplemax.setSizePolicy(sizePolicy)
        self.le_samplemax.setMinimumSize(QtCore.QSize(60, 24))
        self.le_samplemax.setMaximumSize(QtCore.QSize(60, 24))
        self.le_samplemax.setObjectName(_fromUtf8("le_samplemax"))
        self.horizontalLayout_13.addWidget(self.le_samplemax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_12.addWidget(self.gr_sample)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        spacerItem6 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.pb_preview = QtGui.QPushButton(self.layoutWidget)
        self.pb_preview.setObjectName(_fromUtf8("pb_preview"))
        self.horizontalLayout_17.addWidget(self.pb_preview)
        self.pb_alignsave = QtGui.QPushButton(self.layoutWidget)
        self.pb_alignsave.setObjectName(_fromUtf8("pb_alignsave"))
        self.horizontalLayout_17.addWidget(self.pb_alignsave)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        spacerItem7 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.br_outputlog = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.br_outputlog.sizePolicy().hasHeightForWidth())
        self.br_outputlog.setSizePolicy(sizePolicy)
        self.br_outputlog.setMaximumSize(QtCore.QSize(16777215, 110))
        self.br_outputlog.setObjectName(_fromUtf8("br_outputlog"))
        self.verticalLayout.addWidget(self.br_outputlog)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tb_align.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Orbis Map Alignment", None))
        self.gr_input.setTitle(_translate("MainWindow", "Input:", None))
        self.lb_run.setText(_translate("MainWindow", "Run", None))
        self.pb_run.setText(_translate("MainWindow", "choose run", None))
        self.lb_map.setText(_translate("MainWindow", "Map", None))
        self.pb_map.setText(_translate("MainWindow", "choose map", None))
        self.gr_stage.setTitle(_translate("MainWindow", "Stage Alignment:", None))
        self.tb_align.setTabText(self.tb_align.indexOf(self.tab_print), _translate("MainWindow", "Print", None))
        self.tb_align.setTabText(self.tb_align.indexOf(self.tab_wafer), _translate("MainWindow", "Wafer", None))
        self.lb_stagcoord.setText(_translate("MainWindow", "Use stage x, y, z from Orbis Vision.", None))
        item = self.tw_stage.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A", None))
        item = self.tw_stage.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B", None))
        item = self.tw_stage.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "C", None))
        item = self.tw_stage.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sample *", None))
        item = self.tw_stage.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "StagX", None))
        item = self.tw_stage.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "StagY", None))
        __sortingEnabled = self.tw_stage.isSortingEnabled()
        self.tw_stage.setSortingEnabled(False)
        self.tw_stage.setSortingEnabled(__sortingEnabled)
        self.lb_stagz.setText(_translate("MainWindow", "StagZ ", None))
        self.cb_rotonly.setText(_translate("MainWindow", "Rot. only**", None))
        self.le_waferignore.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">*Sample column ignored for wafer.</span></p></body></html>", None))
        self.lb_rotonly.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">**Use </span><span style=\" font-size:7pt; text-decoration: overline;\">BC</span><span style=\" font-size:7pt;\"> for rotation only, no skew.</span></p></body></html>", None))
        self.gr_filter.setTitle(_translate("MainWindow", "Filters:", None))
        self.lb_keepcode.setText(_translate("MainWindow", "keep codes ", None))
        self.lb_omitch.setText(_translate("MainWindow", "omit Ch\'s ", None))
        self.gr_platecoord.setTitle(_translate("MainWindow", "Platemap Coordinate Limits:", None))
        self.lb_xmin.setText(_translate("MainWindow", "x_min ", None))
        self.lb_xmax.setText(_translate("MainWindow", "x_max ", None))
        self.lb_ymin.setText(_translate("MainWindow", "y_min ", None))
        self.lb_ymax.setText(_translate("MainWindow", "y_max ", None))
        self.gr_skip.setTitle(_translate("MainWindow", "Skip Every:", None))
        self.lb_sampleskip.setText(_translate("MainWindow", " samples", None))
        self.lb_colskip.setText(_translate("MainWindow", " columns", None))
        self.lb_rowskip.setText(_translate("MainWindow", " rows", None))
        self.lb_atskip.setText(_translate("MainWindow", " at.%", None))
        self.gr_sample.setTitle(_translate("MainWindow", "Override Sample List:", None))
        self.lb_samplemin.setText(_translate("MainWindow", "sample_min ", None))
        self.lb_samplemax.setText(_translate("MainWindow", "sample_max ", None))
        self.pb_preview.setText(_translate("MainWindow", "Preview output (rotation/skew/points)", None))
        self.pb_alignsave.setText(_translate("MainWindow", "Generate stage and sample list", None))
        self.br_outputlog.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Ready.</span></p></body></html>", None))

import alignprint_rc
